# Tensor vs Parameter

In [4]:
import torch
from torch import nn
from torch import Tensor 


In [16]:
class MyLinear(nn.Module):
    def __init__(self, in_features :int, out_features: int, bias=True):
        super().__init__()
        self.in_features = in_features
        self.out_features = out_features

        self.weights = nn.Parameter(torch.randn(in_features, out_features))
        self.bias = nn.Parameter(torch.randn(out_features))

    def forward(self, x : Tensor):
        return x @ self.weights + self.bias


In [17]:
x = torch.randn(5,7)
x

tensor([[-0.7540, -1.4113, -2.7719, -1.2635, -0.1125, -1.6292,  0.6910],
        [-0.3963, -0.9371,  0.0390,  0.3860, -1.2742, -1.1699, -0.6987],
        [-0.6261,  0.8114, -0.9349,  0.7862,  0.2609, -0.5031, -2.0653],
        [-1.3957, -0.7094,  0.1954,  0.6103, -0.9790, -1.0491,  1.6414],
        [-0.8234, -1.0884, -0.9798, -0.1425,  0.3820, -0.7066, -1.2968]])

In [20]:
layer = MyLinear(7, 12)
layer(x)
layer(x).shape

torch.Size([5, 12])

In [19]:
for value in layer.parameters():
    print(value)

Parameter containing:
tensor([[-0.4373,  0.9162, -0.9937, -1.4457,  1.2842,  0.3717, -0.5025,  1.8465,
         -0.4021, -2.4787, -3.4916,  1.1409],
        [-0.1255,  1.3740,  0.5123, -0.5508,  0.3859,  0.3136, -0.6276,  1.0184,
         -1.7447,  0.7766,  0.3809,  1.1429],
        [ 1.2965, -0.2828, -0.7173, -0.1925,  0.0815, -0.2593,  1.0278,  0.1479,
         -0.9371,  0.6382, -0.1692,  0.3042],
        [-0.1922, -1.7373, -0.4830,  0.0230, -2.6770, -1.1562, -0.4834, -0.5233,
          0.7815, -0.7825,  0.1765, -2.9611],
        [-0.0835,  0.6990,  0.2747, -0.5984, -0.8869, -0.4160, -1.8068, -1.2907,
         -0.8190, -0.4657, -0.3774, -0.8374],
        [-0.1414, -0.5227, -0.1598,  1.3709,  0.2292,  2.7624,  1.4704, -0.6335,
          1.1171,  0.5894, -0.5471,  0.3719],
        [-0.7047,  0.4909,  0.7605, -1.3339, -0.0253, -0.9228,  0.0213,  0.0497,
         -0.1394,  0.9112, -0.5770, -0.6991]], requires_grad=True)
Parameter containing:
tensor([-0.4597, -0.1415, -1.4350,  1.1516, -1

In [21]:
class MyLinearTensor(nn.Module):
    def __init__(self, in_features, out_features, bias=True):
        super().__init__()
        self.in_features = in_features
        self.out_features = out_features 

        self.weights = Tensor(torch.randn(in_features, out_features))
        self.bias = Tensor(torch.randn(out_features))

    def forward(self, x : Tensor):
        return x @ self.weights + self.bias

layerT = MyLinear(7, 12)
layerT(x)

tensor([[-2.9042, -6.1153,  3.8754,  2.7142, -4.9368,  4.9888,  2.3972,  7.7085,
          4.5700, -1.0603, -2.0727, -0.8741],
        [-1.6594,  0.4161,  0.8331,  3.0138, -2.2929,  3.7931,  2.5698,  3.5831,
          2.8548,  3.0971, -1.5520,  1.7841],
        [ 0.5013, -0.6970,  1.1580,  3.8808,  2.0870,  0.8639, -5.7337, -1.8347,
          5.5430,  3.4776, -3.3267,  3.1814],
        [-1.1581,  1.9436, -2.5082, -0.3302, -4.6993,  4.7770,  4.6783,  2.7982,
          1.0504,  0.5612, -1.1633, -2.5134],
        [-0.4042, -1.6464,  3.4230,  3.7326, -2.3025,  1.4835, -2.4468,  3.7676,
          2.8090,  1.6334, -2.7531,  0.1628]], grad_fn=<AddBackward0>)

In [22]:
layerT(x).shape

torch.Size([5, 12])

In [23]:
for value in layerT.parameters():
    print(value)

Parameter containing:
tensor([[ 1.0044e+00, -4.5313e-01, -3.3337e-01,  5.3342e-01,  6.0799e-01,
         -1.5472e+00,  2.9942e-01,  8.3805e-01, -3.7134e-01,  6.5981e-02,
          1.6511e+00,  1.2281e+00],
        [-2.0094e-01,  4.2677e-01, -5.4562e-01, -9.3851e-03,  1.8258e+00,
          5.3629e-02, -2.1525e-01, -2.7510e+00,  7.7101e-01,  1.6096e-01,
         -3.2056e-02,  1.1876e+00],
        [ 2.6770e-01,  2.2710e+00, -2.0812e-01,  3.9148e-03, -6.4484e-02,
         -6.8611e-01,  1.4791e+00, -6.2586e-01, -1.8502e+00, -3.5231e-02,
          5.4698e-01,  1.3511e-01],
        [ 1.6111e+00,  2.6095e-01, -2.3182e+00, -7.8799e-01, -6.9408e-02,
         -4.3716e-01, -1.8725e+00,  1.3119e-01,  9.9571e-01,  4.1554e-01,
         -3.3456e-01, -1.9611e-01],
        [ 1.7729e+00,  1.4838e-01,  7.3569e-02,  3.7934e-03, -2.4655e-01,
         -2.1238e+00, -1.6422e+00,  3.0338e-01, -8.5535e-01, -1.3915e+00,
          9.1688e-02, -5.2302e-01],
        [ 2.3124e-03,  2.9802e-01,  6.9491e-02, -2.9685e-0

# AutoGrad for Linear Regression

$$
    y = 2x + 1
$$

In [26]:
import numpy as np

# create dummy data for training 
x_values = [i for i in range(11)]
x_train = np.array(x_values, dtype=np.float32)
x_train = x_train.reshape(-1,1) # ROW로 만들어줌 (Col이 1인 ROW 여러 개 의미)
x_train

array([[ 0.],
       [ 1.],
       [ 2.],
       [ 3.],
       [ 4.],
       [ 5.],
       [ 6.],
       [ 7.],
       [ 8.],
       [ 9.],
       [10.]], dtype=float32)

In [27]:
y_values = [ 2*x + 1 for x in x_values]
y_values


[1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21]

In [29]:
y_train = np.array(y_values, dtype=np.float32)
y_train = y_train.reshape(-1, 1)
y_train


array([[ 1.],
       [ 3.],
       [ 5.],
       [ 7.],
       [ 9.],
       [11.],
       [13.],
       [15.],
       [17.],
       [19.],
       [21.]], dtype=float32)

In [93]:
import torch
from torch.autograd import Variable

HIDDEN_DIM = 1

class LinearRegression(torch.nn.Module):
    def __init__(self, inputSize, outputSize):
        super(LinearRegression, self).__init__()
        self.linear = torch.nn.Linear(inputSize, outputSize)
        #self.linear2 = torch.nn.Linear(HIDDEN_DIM, outputSize)

    def forward(self, x):
        out = self.linear(x)
        #out = self.linear2(out)
        return out

In [101]:
inputDim = 1 # take variable 'x' 
outputDim = 1 # takes variable 'y'  
learningRate = 0.01 
epochs = 100

model = LinearRegression(inputDim, outputDim)

if torch.cuda.is_available():
    model.cuda()

In [102]:
criterion = torch.nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=learningRate)


In [103]:
for epoch in range(epochs):
    if torch.cuda.is_available():
        inputs = Variable(torch.from_numpy(x_train).cuda())
        labels = Variable(torch.from_numpy(y_train).cuda())
    else:
        inputs = Variable(torch.from_numpy(x_train))
        labels = Variable(torch.from_numpy(y_train))

    optimizer.zero_grad()

    outputs = model(inputs)

    loss = criterion(outputs, labels)
    loss.backward()

    optimizer.step()

    print(f'epoch {epoch}, loss {loss.item()}')

epoch 0, loss 62.466346740722656
epoch 1, loss 5.0957722663879395
epoch 2, loss 0.4162299931049347
epoch 3, loss 0.03452688083052635
epoch 4, loss 0.003386527067050338
epoch 5, loss 0.0008400771766901016
epoch 6, loss 0.0006260964437387884
epoch 7, loss 0.0006024108733981848
epoch 8, loss 0.0005943237338215113
epoch 9, loss 0.0005875776405446231
epoch 10, loss 0.0005810072761960328
epoch 11, loss 0.0005745263770222664
epoch 12, loss 0.0005680934991687536
epoch 13, loss 0.0005617544520646334
epoch 14, loss 0.0005554808885790408
epoch 15, loss 0.0005492804921232164
epoch 16, loss 0.0005431605386547744
epoch 17, loss 0.0005370787112042308
epoch 18, loss 0.0005310876877047122
epoch 19, loss 0.0005251556285656989
epoch 20, loss 0.000519289867952466
epoch 21, loss 0.0005134879029355943
epoch 22, loss 0.0005077639943920076
epoch 23, loss 0.0005020847893320024
epoch 24, loss 0.0004964863765053451
epoch 25, loss 0.0004909386043436825
epoch 26, loss 0.0004854646685998887
epoch 27, loss 0.0004800

In [106]:
with torch.no_grad():
    if torch.cuda.is_available():
        predicted = model(Variable(torch.from_numpy(x_train).cuda())).cpu().data.numpy()
    else:
        predicted = model(Variable(torch.from_numpy(x_train))).data.numpy()


for p, l in zip(predicted, labels):
    print(p, l)

[0.9727964] tensor([1.])
[2.9767141] tensor([3.])
[4.980632] tensor([5.])
[6.9845495] tensor([7.])
[8.988467] tensor([9.])
[10.992385] tensor([11.])
[12.996303] tensor([13.])
[15.00022] tensor([15.])
[17.004137] tensor([17.])
[19.008055] tensor([19.])
[21.011972] tensor([21.])
