# Numpy to Tensor

In [3]:
import numpy as np
n_array = np.arange(10).reshape(2,5)
print(n_array)
print('ndim:', n_array.ndim, ' shape:', n_array.shape)

[[0 1 2 3 4]
 [5 6 7 8 9]]
ndim: 2  shape: (2, 5)


In [4]:
import torch 

t_array = torch.FloatTensor(n_array)
print(t_array)
print(t_array.size())

tensor([[0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.]])
torch.Size([2, 5])


In [5]:
print(t_array.shape)
print(t_array.ndim)
print(t_array.size())

torch.Size([2, 5])
2
torch.Size([2, 5])


# Array to Tensor

In [6]:
# Data to tensor 
data = [[3,5], [10,5]]
x_data = torch.tensor(data)
x_data

tensor([[ 3,  5],
        [10,  5]])

In [7]:
# ndArray to Tensor
nd_array_ex = np.array(data)
tensor_array = torch.from_numpy(nd_array_ex)
tensor_array

tensor([[ 3,  5],
        [10,  5]])

In [8]:
# numpy like operations 

data = [[3, 5, 20], [10, 5, 50], [1, 5, 10]]
x_data = torch.tensor(data)
x_data

tensor([[ 3,  5, 20],
        [10,  5, 50],
        [ 1,  5, 10]])

In [9]:
x_data[1:]

tensor([[10,  5, 50],
        [ 1,  5, 10]])

In [10]:
x_data[:2, 1:]

tensor([[ 5, 20],
        [ 5, 50]])

In [11]:
x_data.flatten()


tensor([ 3,  5, 20, 10,  5, 50,  1,  5, 10])

In [12]:
torch.ones_like(x_data)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

In [13]:
x_data.numpy()

array([[ 3,  5, 20],
       [10,  5, 50],
       [ 1,  5, 10]])

In [14]:
x_data.shape


torch.Size([3, 3])

In [15]:
x_data.dtype

torch.int64

In [16]:
x_data.device

device(type='cpu')

In [17]:
if torch.cuda.is_available():
    x_data_cuda = x_data.to('cuda')

    x_data_cuda.device
    # device(type='cuda', index=0)

# Tensor Handling

In [18]:
tensor_ex = torch.rand(size=(2,3,2))
tensor_ex

tensor([[[0.8608, 0.4281],
         [0.8965, 0.6440],
         [0.9395, 0.2398]],

        [[0.1693, 0.0074],
         [0.2215, 0.1218],
         [0.1782, 0.6811]]])

In [19]:
tensor_ex.view([-1,6])

tensor([[0.8608, 0.4281, 0.8965, 0.6440, 0.9395, 0.2398],
        [0.1693, 0.0074, 0.2215, 0.1218, 0.1782, 0.6811]])

In [20]:
tensor_ex.reshape([-1, 6])

tensor([[0.8608, 0.4281, 0.8965, 0.6440, 0.9395, 0.2398],
        [0.1693, 0.0074, 0.2215, 0.1218, 0.1782, 0.6811]])

In [21]:
a = torch.zeros(3,2)
b = a.view(2,3)
a.fill_(1)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [22]:
a

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [23]:
b

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [24]:
a = torch.zeros(3,2)
b = a.t().reshape(6)
a.fill_(1)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [25]:
a

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [26]:
b

tensor([0., 0., 0., 0., 0., 0.])

# Pytorch squeeze and unsqueeze

[https://stackoverflow.com/questions/61598771/pytorch-squeeze-and-unsqueeze](https://stackoverflow.com/questions/61598771/pytorch-squeeze-and-unsqueeze)

![](https://i.stack.imgur.com/9AJJA.png)

In [27]:
tensor_ex = torch.rand(size = (2, 1, 2))
tensor_ex

tensor([[[0.3990, 0.1065]],

        [[0.5790, 0.1247]]])

In [28]:
tensor_ex.squeeze()
#tensor_ex

tensor([[0.3990, 0.1065],
        [0.5790, 0.1247]])

In [29]:
tensor_ex = torch.rand(size = (2, 2))
tensor_ex

tensor([[0.5639, 0.7459],
        [0.7050, 0.0121]])

In [30]:
tensor_ex.unsqueeze(0).shape

torch.Size([1, 2, 2])

In [31]:
tensor_ex.unsqueeze(1).shape

torch.Size([2, 1, 2])

In [32]:
tensor_ex # 원래 값은 안 변함 

tensor([[0.5639, 0.7459],
        [0.7050, 0.0121]])

# Tensor Operations

기본적으로 tensor의 operations는 numpy와 동일

In [33]:
n1 = np.arange(10).reshape(2,5)
n2 = np.arange(10).reshape(5,2)
t1 = torch.FloatTensor(n1)
t2 = torch.FloatTensor(n2)

In [34]:
t1 + t1

tensor([[ 0.,  2.,  4.,  6.,  8.],
        [10., 12., 14., 16., 18.]])

In [35]:
t1 - t1

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [36]:
t1 + 10

tensor([[10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19.]])

In [37]:
t1 * 10

tensor([[ 0., 10., 20., 30., 40.],
        [50., 60., 70., 80., 90.]])

In [38]:
n2 = np.arange(10).reshape(5,2)
t2 = torch.FloatTensor(n2)

t1.mm(t2)

tensor([[ 60.,  70.],
        [160., 195.]])

In [39]:
t1.dot(t2)

RuntimeError: 1D tensors expected, but got 2D and 2D tensors

In [40]:
t1.matmul(t2)

tensor([[ 60.,  70.],
        [160., 195.]])

In [45]:
a = torch.rand(5,2,3) # 첫자리는 주로 배치 이로 2x3행렬
b = torch.rand(3) # 3x1 행렬(또는 벡터)


In [46]:
a.mm(b)

RuntimeError: self must be a matrix

In [47]:
a.matmul(b) # 알아서 브로드캐스팅 ==> 

tensor([[0.3903, 0.9696],
        [0.3445, 0.6572],
        [0.0758, 0.2502],
        [0.2627, 0.9545],
        [0.7210, 0.9778]])

In [49]:
a.matmul(b).shape # 5x2x1 행렬 출력

torch.Size([5, 2])

In [57]:
print(a[0].mm(torch.unsqueeze(b,1)))
a[0].mm(torch.unsqueeze(b,1)).squeeze()

tensor([[0.3903],
        [0.9696]])


tensor([0.3903, 0.9696])

In [52]:
torch.unsqueeze(b,1).shape

torch.Size([3, 1])

In [53]:
b

tensor([0.2376, 0.0634, 0.8667])

In [54]:
b.shape

torch.Size([3])

# Tensor Operations for ML/DL formula

In [58]:
import torch
import torch.nn.functional as F 

tensor = torch.FloatTensor([0.5, 0.7, 0.1])
h_tensor = F.softmax(tensor, dim=0)
h_tensor

tensor([0.3458, 0.4224, 0.2318])

In [63]:
y = torch.randint(5, (10,5))
y

tensor([[2, 4, 1, 2, 2],
        [1, 1, 2, 2, 2],
        [3, 3, 2, 4, 0],
        [1, 2, 0, 2, 4],
        [3, 3, 2, 1, 0],
        [0, 3, 2, 0, 1],
        [2, 2, 0, 3, 2],
        [0, 1, 2, 1, 4],
        [1, 0, 4, 4, 0],
        [4, 2, 0, 4, 1]])

In [66]:
y_label = y.argmax(dim = 1)
y_label

tensor([1, 2, 3, 4, 0, 1, 3, 4, 2, 0])

In [67]:
F.one_hot(y_label)

tensor([[0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 1],
        [1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 1],
        [0, 0, 1, 0, 0],
        [1, 0, 0, 0, 0]])

In [70]:
import itertools
a = [1,2,3]
b =[4,5]
list(itertools.product(a,b))

[(1, 4), (1, 5), (2, 4), (2, 5), (3, 4), (3, 5)]

In [71]:
tensor_a = torch.tensor(a)
tensor_b = torch.tensor(b)
torch.cartesian_prod(tensor_a, tensor_b)

tensor([[1, 4],
        [1, 5],
        [2, 4],
        [2, 5],
        [3, 4],
        [3, 5]])

# AutoGrad

In [91]:
w = torch.tensor(2.0, requires_grad=True)
y = w**2
z = 10*y + 25
z.backward()

$$
z = 10 * w^2 + 25
$$

$$
{dz \over dw} = 20 * w 
$$

In [92]:
w.grad

tensor(40.)

In [89]:
a = torch.tensor([2., 3.], requires_grad=True)
b = torch.tensor([6., 4.], requires_grad=True)
Q = 3 * a**3 - b**2
external_grad = torch.tensor([1., 1.])
Q.backward(gradient=external_grad)

a.grad

tensor([36., 81.])

$$
Q = 3 * a^3 - b^2
$$

$$
 {dQ \over da} = 9a^2
$$

$$
 {dQ \over db} = -2b
$$


In [90]:
b.grad

tensor([-12.,  -8.])